/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fathkdyxgeeokxeobxqp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhdGhrZHl4Z2Vlb2t4ZW9ieHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNTA5NTEsImV4cCI6MjA4NjgyNjk1MX0.bmFK3oSm4-f6Yp3e39l1yDhT29GIkfW4tHXSc-vBXR8"